items{
signingRequest{
`-----BEGIN CERTIFICATE REQUEST-----
MIICgjCCAgkCAQAwgcUxJjAkBgkqhkiG9w0BCQEWF2F0aG9ybnRvbkBhcm1vZ2V0
dG8ubmV0MQswCQYDVQQIDAJBTDEfMB0GA1UEAwwWKi5iaC02OS53ZWJob3N0Ym94
Lm5ldDETMBEGA1UEBwwKQmlybWluZ2hhbTEmMCQGA1UECgwdQWxnb3J5bXRobSBJ
bnRlcm5hdGlvbmFsIEluYy4xIzAhBgNVBAsMGkRldmVsb3BtZW50IGFuZCBQcm9k
dWN0aW9uMQswCQYDVQQGEwJVUzB2MBAGByqGSM49AgEGBSuBBAAiA2IABEDlR0H6
opyTKDA1KMFLHrCnCIczCIAZ96SF1ebKjA5rpzItnxw72m+NnFm5Re1uzDt1rge0
nxlZXANoBR4jZPYihHwdlKQfB+N/V3u36n9VULrV9jIYcJ97ZgjnLnlA66CBwzAX
BgkqhkiG9w0BCQcxCgwIMTIzNDU2NzgwgacGCSqGSIb3DQEJDjGBmTCBljCBkwYD
VR0RBIGLMIGIghYqLmJoLTY5LndlYmhvc3Rib3gubmV0gg8qLmFybW9nZXR0by5u
ZXSCECouYWxnb3J5bXRobS5jb22CDyouYXJtb2dldHRvLmNvbYIPKi5mZXRpc2hx
dW8uY29tghcqLnJveWFsdHlzdGFydHNoZXJlLmNvbYIQKi4yMDguOTEuMTk5LjEx
ODAKBggqhkjOPQQDAgNnADBkAjBJeVdDmSIDzSfZKiByiZoSWHrMJN0AAMjdVBlz
GLNGoEE/lWW8aonXHLyFF3rOk7gCMFI2DWaiT9QDhPr6Pz/MZ+rlzFmkq1DrgW2i
L9CBznpKxrmpKGuDGBK3aLNi8wWWwA==
-----END CERTIFICATE REQUEST-----`
 }
certificate{
`-----BEGIN CERTIFICATE-----
MIIElzCCBB6gAwIBAgIEG67lizAKBggqhkjOPQQDAjCBxTEfMB0GA1UEAwwWKi5i
aC02OS53ZWJob3N0Ym94Lm5ldDELMAkGA1UECAwCQUwxJjAkBgkqhkiG9w0BCQEW
F2F0aG9ybnRvbkBhcm1vZ2V0dG8ubmV0MQswCQYDVQQGEwJVUzEjMCEGA1UECwwa
RGV2ZWxvcG1lbnQgYW5kIFByb2R1Y3Rpb24xJjAkBgNVBAoMHUFsZ29yeW10aG0g
SW50ZXJuYXRpb25hbCBJbmMuMRMwEQYDVQQHDApCaXJtaW5naGFtMB4XDTI1MDUw
NjE0MjExNloXDTI2MDUwNjE0MjExNlowgcUxHzAdBgNVBAMMFiouYmgtNjkud2Vi
aG9zdGJveC5uZXQxCzAJBgNVBAgMAkFMMSYwJAYJKoZIhvcNAQkBFhdhdGhvcm50
b25AYXJtb2dldHRvLm5ldDELMAkGA1UEBhMCVVMxIzAhBgNVBAsMGkRldmVsb3Bt
ZW50IGFuZCBQcm9kdWN0aW9uMSYwJAYDVQQKDB1BbGdvcnltdGhtIEludGVybmF0
aW9uYWwgSW5jLjETMBEGA1UEBwwKQmlybWluZ2hhbTB2MBAGByqGSM49AgEGBSuB
BAAiA2IABEDlR0H6opyTKDA1KMFLHrCnCIczCIAZ96SF1ebKjA5rpzItnxw72m+N
nFm5Re1uzDt1rge0nxlZXANoBR4jZPYihHwdlKQfB+N/V3u36n9VULrV9jIYcJ97
ZgjnLnlA66OCAdswggHXMB0GA1UdDgQWBBTUiqztDDjdwcTXWUnYMnLnKv37hzAJ
BgNVHRMEAjAAMIH1BgNVHSMEge0wgeqAFNSKrO0MON3BxNdZSdgycucq/fuHoYHL
pIHIMIHFMR8wHQYDVQQDDBYqLmJoLTY5LndlYmhvc3Rib3gubmV0MQswCQYDVQQI
DAJBTDEmMCQGCSqGSIb3DQEJARYXYXRob3JudG9uQGFybW9nZXR0by5uZXQxCzAJ
BgNVBAYTAlVTMSMwIQYDVQQLDBpEZXZlbG9wbWVudCBhbmQgUHJvZHVjdGlvbjEm
MCQGA1UECgwdQWxnb3J5bXRobSBJbnRlcm5hdGlvbmFsIEluYy4xEzARBgNVBAcM
CkJpcm1pbmdoYW2CBBuu5YswHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMC
MIGTBgNVHREEgYswgYiCFiouYmgtNjkud2ViaG9zdGJveC5uZXSCDyouYXJtb2dl
dHRvLm5ldIIQKi5hbGdvcnltdGhtLmNvbYIPKi5hcm1vZ2V0dG8uY29tgg8qLmZl
dGlzaHF1by5jb22CFyoucm95YWx0eXN0YXJ0c2hlcmUuY29tghAqLjIwOC45MS4x
OTkuMTE4MAoGCCqGSM49BAMCA2cAMGQCMBHidQhB9m9gCubt7iNo9v8VfRofDTe4
CGXwcs/Fkv7JRH8Goik24+vcr1nYRiXKHgIwZ3ziAIp8u5XB5NskP6S78uTuPyYZ
zihLSR81IEFy0r7gTh8W9vBqcNHaAeowNQgv
-----END CERTIFICATE-----`
 }
key{
`-----BEGIN EC PRIVATE KEY-----
MIGkAgEBBDASTgFa0R2iSxdhNastpmHdAxMNdZNEuC+Wv33fcsQjJvSS1E+w9T1Z
MFsNt6vEdOKgBwYFK4EEACKhZANiAARA5UdB+qKckygwNSjBSx6wpwiHMwiAGfek
hdXmyowOa6cyLZ8cO9pvjZxZuUXtbsw7da4HtJ8ZWVwDaAUeI2T2IoR8HZSkHwfj
f1d7t+p/VVC61fYyGHCfe2YI5y55QOs=
-----END EC PRIVATE KEY-----`
 }
}

const certExtractor()=>{
         let results = [];
    foreach(item in items){
         results.append(item.value);
    }
  results? : let path ="/tmp"
             && await const promise1 = writeFile('path/extracted.der', results,{echo "done!"})
             && await const promise2 = writeFile('path/extracted.pem', results,{echo "done!"})
             
             || echo null;
  };
  
certExtractor(items);

